
#include "LinearMath/btMatrix3x3.h"

inline btMatrix3x3 get_btMatrix3x3(const octet::mat4t &m) {
  return btMatrix3x3(m.x().x(), m.x().y(), m.x().z(), m.y().x(), m.y().y(), m.y().z(), m.z().x(), m.z().y(), m.z().z());
}

inline btVector3 get_btVector3(const octet::vec3 &v) {
  return btVector3(v.x(),  v.y(), v.z());
}

inline octet::vec4_ret get_vec4(const btVector3 &v, float w) {
  return octet::vec4(v.x(),  v.y(), v.z(), w);
}

inline octet::mat4t_ret get_mat4t(btMatrix3x3 &m, btVector3 &p) {
  return octet::mat4t(get_vec4(m[0], 0), get_vec4(m[1], 0), get_vec4(m[2], 0), get_vec4(p, 1));
}

inline octet::vec3_ret get_vec3(const btVector3 &v) {
  return octet::vec3(v.x(),  v.y(), v.z());
}


#include "btBulletCollisionCommon.h"
#include "btBulletDynamicsCommon.h"


#include "BulletCollision/BroadphaseCollision/btAxisSweep3.cpp"
#include "BulletCollision/BroadphaseCollision/btBroadphaseProxy.cpp"
#include "BulletCollision/BroadphaseCollision/btCollisionAlgorithm.cpp"
#include "BulletCollision/BroadphaseCollision/btDbvt.cpp"
#include "BulletCollision/BroadphaseCollision/btDbvtBroadphase.cpp"
#include "BulletCollision/BroadphaseCollision/btDispatcher.cpp"
#include "BulletCollision/BroadphaseCollision/btMultiSapBroadphase.cpp"
#include "BulletCollision/BroadphaseCollision/btOverlappingPairCache.cpp"
#include "BulletCollision/BroadphaseCollision/btQuantizedBvh.cpp"
#include "BulletCollision/BroadphaseCollision/btSimpleBroadphase.cpp"
#include "BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btBoxBoxDetector.cpp"
#include "BulletCollision/CollisionDispatch/btCollisionDispatcher.cpp"
#include "BulletCollision/CollisionDispatch/btCollisionObject.cpp"
#include "BulletCollision/CollisionDispatch/btCollisionWorld.cpp"
#include "BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.cpp"
#include "BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btGhostObject.cpp"
#include "BulletCollision/CollisionDispatch/btHashedSimplePairCache.cpp"
#include "BulletCollision/CollisionDispatch/btInternalEdgeUtility.cpp"
#include "BulletCollision/CollisionDispatch/btInternalEdgeUtility.h"
#include "BulletCollision/CollisionDispatch/btManifoldResult.cpp"
#include "BulletCollision/CollisionDispatch/btSimulationIslandManager.cpp"
#include "BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.cpp"
#include "BulletCollision/CollisionDispatch/btUnionFind.cpp"
#include "BulletCollision/CollisionDispatch/SphereTriangleDetector.cpp"
#include "BulletCollision/CollisionShapes/btBoxShape.cpp"
#include "BulletCollision/CollisionShapes/btBox2dShape.cpp"
#include "BulletCollision/CollisionShapes/btBvhTriangleMeshShape.cpp"
#include "BulletCollision/CollisionShapes/btCapsuleShape.cpp"
#include "BulletCollision/CollisionShapes/btCollisionShape.cpp"
#include "BulletCollision/CollisionShapes/btCompoundShape.cpp"
#include "BulletCollision/CollisionShapes/btConcaveShape.cpp"
#include "BulletCollision/CollisionShapes/btConeShape.cpp"
#include "BulletCollision/CollisionShapes/btConvexHullShape.cpp"
#include "BulletCollision/CollisionShapes/btConvexInternalShape.cpp"
#include "BulletCollision/CollisionShapes/btConvexPointCloudShape.cpp"
#include "BulletCollision/CollisionShapes/btConvexPolyhedron.cpp"
#include "BulletCollision/CollisionShapes/btConvexShape.cpp"
#include "BulletCollision/CollisionShapes/btConvex2dShape.cpp"
#include "BulletCollision/CollisionShapes/btConvexTriangleMeshShape.cpp"
#include "BulletCollision/CollisionShapes/btCylinderShape.cpp"
#include "BulletCollision/CollisionShapes/btEmptyShape.cpp"
#include "BulletCollision/CollisionShapes/btHeightfieldTerrainShape.cpp"
#include "BulletCollision/CollisionShapes/btMinkowskiSumShape.cpp"
#include "BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.cpp"
#include "BulletCollision/CollisionShapes/btMultiSphereShape.cpp"
#include "BulletCollision/CollisionShapes/btOptimizedBvh.cpp"
#include "BulletCollision/CollisionShapes/btPolyhedralConvexShape.cpp"
#include "BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.cpp"
#include "BulletCollision/CollisionShapes/btShapeHull.cpp"
#include "BulletCollision/CollisionShapes/btSphereShape.cpp"
#include "BulletCollision/CollisionShapes/btStaticPlaneShape.cpp"
#include "BulletCollision/CollisionShapes/btStridingMeshInterface.cpp"
#include "BulletCollision/CollisionShapes/btTetrahedronShape.cpp"
#include "BulletCollision/CollisionShapes/btTriangleBuffer.cpp"
#include "BulletCollision/CollisionShapes/btTriangleCallback.cpp"
#include "BulletCollision/CollisionShapes/btTriangleIndexVertexArray.cpp"
#include "BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.cpp"
#include "BulletCollision/CollisionShapes/btTriangleMesh.cpp"
#include "BulletCollision/CollisionShapes/btTriangleMeshShape.cpp"
#include "BulletCollision/CollisionShapes/btUniformScalingShape.cpp"
/*#include "BulletCollision/Gimpact/btContactProcessing.cpp"
#include "BulletCollision/Gimpact/btGenericPoolAllocator.cpp"
#include "BulletCollision/Gimpact/btGImpactBvh.cpp"
#include "BulletCollision/Gimpact/btGImpactCollisionAlgorithm.cpp"
#include "BulletCollision/Gimpact/btGImpactQuantizedBvh.cpp"
#include "BulletCollision/Gimpact/btGImpactShape.cpp"
#include "BulletCollision/Gimpact/btTriangleShapeEx.cpp"
#include "BulletCollision/Gimpact/gim_box_set.cpp"
#include "BulletCollision/Gimpact/gim_contact.cpp"
#include "BulletCollision/Gimpact/gim_memory.cpp"
#include "BulletCollision/Gimpact/gim_tri_collision.cpp"
*/
#include "BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.cpp"
#include "BulletCollision/NarrowPhaseCollision/btConvexCast.cpp"
#include "BulletCollision/NarrowPhaseCollision/btGjkConvexCast.cpp"
#include "BulletCollision/NarrowPhaseCollision/btGjkEpa2.cpp"
#include "BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.cpp"
#include "BulletCollision/NarrowPhaseCollision/btGjkPairDetector.cpp"
#include "BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.cpp"
#include "BulletCollision/NarrowPhaseCollision/btPersistentManifold.cpp"
#include "BulletCollision/NarrowPhaseCollision/btRaycastCallback.cpp"
#include "BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.cpp"
#include "BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.cpp"
#include "BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.cpp"

#include "BulletDynamics/Character/btKinematicCharacterController.cpp"
#include "BulletDynamics/ConstraintSolver/btConeTwistConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btContactConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btFixedConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btGearConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btHinge2Constraint.cpp"
#include "BulletDynamics/ConstraintSolver/btHingeConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btPoint2PointConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.cpp"
#include "BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.cpp"
#include "BulletDynamics/ConstraintSolver/btSliderConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btTypedConstraint.cpp"
#include "BulletDynamics/ConstraintSolver/btUniversalConstraint.cpp"
#include "BulletDynamics/Dynamics/btDiscreteDynamicsWorld.cpp"
#include "BulletDynamics/Dynamics/btRigidBody.cpp"
#include "BulletDynamics/Dynamics/btSimpleDynamicsWorld.cpp"
#include "BulletDynamics/Vehicle/btRaycastVehicle.cpp"
#include "BulletDynamics/Vehicle/btWheelInfo.cpp"
#include "BulletDynamics/Featherstone/btMultiBody.cpp"
#include "BulletDynamics/Featherstone/btMultiBodyConstraintSolver.cpp"
#include "BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.cpp"
#include "BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.cpp"
#include "BulletDynamics/Featherstone/btMultiBodyConstraint.cpp"
#include "BulletDynamics/Featherstone/btMultiBodyPoint2Point.cpp"
#include "BulletDynamics/Featherstone/btMultiBodyJointMotor.cpp"
#include "BulletDynamics/MLCPSolvers/btDantzigLCP.cpp"
#include "BulletDynamics/MLCPSolvers/btMLCPSolver.cpp"
#include "BulletDynamics/MLCPSolvers/btLemkeAlgorithm.cpp"

#include "LinearMath/btAlignedAllocator.cpp"
#include "LinearMath/btConvexHull.cpp"
#include "LinearMath/btConvexHullComputer.cpp"
#include "LinearMath/btGeometryUtil.cpp"
#include "LinearMath/btPolarDecomposition.cpp"
#include "LinearMath/btQuickprof.cpp"
#include "LinearMath/btSerializer.cpp"
#include "LinearMath/btVector3.cpp"
